version: '3.9'

networks:
  network2:
    name: network2

services:
#  composer:
#    image: composer
#    volumes:
#      - .:/app
#    working_dir: /app

  php-apache:
    build:
      context:
        ./docker/images/php
    container_name: php-apache
    restart: always
    ports:
      - ${HOST_HTTP_PORT}:80
      - ${HOST_HTTPS_PORT}:443
    volumes:
      - ${WORK_DIR}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${APACHE_LOG_VOLUME}:/var/log/apache2
    networks:
      - network2
    depends_on:
      - mysql

  mysql:
    build:
      context:
        ./docker/images/mysql
    container_name: mysql
    restart: always
    ports:
      - ${HOST_MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_VOLUME}:/var/lib/mysql
    networks:
      - network2

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - ${HOST_HTTP_PORT_PHPMYADMIN}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: ${HOST_MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - network2
    depends_on:
      - mysql